services:
  postgres:
    image: postgres:16
    container_name: job-tracker-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: jobtracker_user
      POSTGRES_PASSWORD: localpassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: